### PR TITLE
Add default to ActivityIndicator export

### PR DESCRIPTION
**Pull request by greglobinski**
The issue is described here https://github.com/airbnb/enzyme/issues/1546
Because `ActivityIndicator` was exported  as 'named export' and declared as an arrow function the shallow method in `TopicsList.test.js` `when topics are loading` test rendered it as `<Component />` not as it should as `<ActivityIndicator />`

There was a different solution, changing `ActivityIndicator` to a normal named function 
```
export function ActivityIndicator() {
    return (
        <p>Loading</p>
    );
}
```
but I've chosen to make it a `default` export. This way the code is more consistent

### CODE REVIEW

**Comment by kgajowy** [comment]
@greglobinski if I understood the point correctly, shouldn't be some snapshots replaced?

**Comment by greglobinski** [comment]
@kgajowy No, the [snapshot]( https://github.com/warsawjs/topics-manager/blob/master/src/topic/components/__tests__/__snapshots__/TopicsList.test.js.snap) is OK,


```
exports[`<TopicsList> when topics are loading should match snapshot 1`] = `
<Section>
  <Text
    type="primary"
  >
    Zgłoszone tematy
  </Text>
  <ActivityIndicator />
</Section>
`;
```

but the [test](https://github.com/warsawjs/topics-manager/blob/master/src/topic/components/__tests__/TopicsList.test.js) 'when topics are loading'  fails (on my localhost) because the shallow method returns something like this

```
<Section>
  <Text
    type="primary"
  >
    Zgłoszone tematy
  </Text>
  <Component />
</Section>
`;
```
the `<Component />` instead `<ActivityIndicator  />`

**Comment by greglobinski** [comment]
@kgajowy 
What do you mean by "why that behavior is different"?

**Comment by greglobinski** [comment]
@kgajowy 
If there is a different behavior of `jest/enzyme` on my localhost and yours it could be because of the [issue](https://github.com/warsawjs/topics-manager/issues/7), because of it I have to use the default `jest` installed with the `create-react-app` and that is the `20.0.4`, the `jest` installed in the repo is `22.4.3`, maybe that's the reason.

**Comment by greglobinski** [comment]
@kgajowy 
With the [workaround](https://github.com/warsawjs/topics-manager/issues/7#issuecomment-394144882) I've found, the issue has gone, so maybe it's not necessary to merge the PR.
However, it makes the code more consistent, after all there is only one export in the file (ActivityIndicator.js), so why not `default`.

**Comment by Tuhaj** [comment]
yep, it's more consistent so we merge!

**Pull request merged**
